"""empty message

Revision ID: 31085012d9b0
Revises: 02a351fe5e83
Create Date: 2024-04-24 04:26:15.443412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31085012d9b0'
down_revision = '02a351fe5e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
