"""empty message

Revision ID: 864c8ae51c6b
Revises: fa0f14f5a6d0
Create Date: 2024-04-24 17:20:53.425386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864c8ae51c6b'
down_revision = 'fa0f14f5a6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
