"""empty message

Revision ID: 96fac017587c
Revises: 0fc51f4e1d6d
Create Date: 2024-04-26 00:37:39.532808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96fac017587c'
down_revision = '0fc51f4e1d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=120), nullable=False))
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
